import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results; 
    callback divide-income(string);

    background: #fcfffc;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                //x:0;y:0;
                text: "Enter Total income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                color: black;
            }
        }
        Row{
           income := LineEdit {
                font-size: 16px;
                horizontal-alignment: center;
            
                placeholder-text: "Enter your number";
                height: 35px;
            }
        }
        Row{
            Button {

                text: "Calculate";
                primary: true;
                clicked => {divide-income(income.text)}
                height: 35px;
            }
        }

        Row{
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background:#f2f2f2 ;
                    Text {
                        color: black;
                        horizontal-alignment: center;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
